/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package scctp1.gui;

import javax.swing.*;
import scctp1.Mundo;
import scctp1.Simulacao;


/**
 *
 * @author MiguelDiogo
 */
public class JanelaNovoMundo extends JFrame {

    /**
     * Creates new form JanelaNovoMundo
     * @param mundo
     */
    
    //private Mundo mundo;
    

    
    /**
     *
     */
    public JanelaNovoMundo() {
        initComponents();
        setTitle("Novo Mundo");
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comprimentoInput = new javax.swing.JTextField();
        larguraInput = new javax.swing.JTextField();
        numeroOvelhasInput = new javax.swing.JTextField();
        numeroLobosInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        unidadesLimiteInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        unidadeTempoInput = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        SimularButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Comprimento");

        jLabel2.setText("Largura");

        jLabel5.setText("Número de Ovelhas");

        jLabel6.setText("Número de Lobos");

        comprimentoInput.setColumns(8);
        comprimentoInput.setText("51");

        larguraInput.setColumns(8);
        larguraInput.setText("51");

        numeroOvelhasInput.setColumns(8);
        numeroOvelhasInput.setText("100");
        numeroOvelhasInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroOvelhasInputActionPerformed(evt);
            }
        });

        numeroLobosInput.setColumns(8);
        numeroLobosInput.setText("30");
        numeroLobosInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroLobosInputActionPerformed(evt);
            }
        });

        jLabel7.setText("Unidade de Tempo (s)");

        unidadesLimiteInput.setColumns(8);
        unidadesLimiteInput.setText("5000");

        jLabel8.setText("Unidades Limite (s)");

        unidadeTempoInput.setColumns(8);
        unidadeTempoInput.setText("0.006");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comprimentoInput)
                                .addComponent(larguraInput)
                                .addComponent(numeroOvelhasInput)
                                .addComponent(numeroLobosInput))
                            .addComponent(unidadeTempoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unidadesLimiteInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comprimentoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(larguraInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeroOvelhasInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numeroLobosInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel7)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(unidadeTempoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(unidadesLimiteInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        SimularButton.setText("Simular");
        SimularButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimularButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SimularButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(SimularButton))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(javax.swing.UIManager.getDefaults().getColor("window")));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(javax.swing.UIManager.getDefaults().getColor("window"));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(2);
        jTextArea1.setText("Insira as configurações do mundo a ser criado.");
        jTextArea1.setBorder(null);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SimularButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimularButtonActionPerformed
        // TODO add your handling code here:

        boolean sucesso = true;
        
        int comprimento = 0, largura = 0, numeroOvelhas = 0, numeroLobos = 0;
        double unidadeTempo = 0, unidadesLimite = 0;
        try {
            comprimento = Integer.parseInt(comprimentoInput.getText());
        }
        catch (NumberFormatException e) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "Comprimento tem que ser um inteiro maior que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);

        }
        
        if (comprimento <= 0) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "Comprimento tem que ser um inteiro maior que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            largura = Integer.parseInt(larguraInput.getText());
        }
        catch (NumberFormatException e) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "Largura tem que ser um inteiro maior que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);

        }
        
        if (largura <= 0) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "Largura tem que ser um inteiro maior que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            numeroLobos = Integer.parseInt(numeroLobosInput.getText());
        }
        catch (NumberFormatException e) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "Numero de Lobos tem que ser um inteiro maior ou igual que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);

        }
        
        if (numeroLobos < 0) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "Numero de Lobos tem que ser um inteiro maior ou igual que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            numeroOvelhas = Integer.parseInt(numeroOvelhasInput.getText());
        }
        catch (NumberFormatException e) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "Numero de Ovelhas tem que ser um inteiro maior ou igual que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);

        }
        
        if (numeroOvelhas < 0) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "Numero de Ovelhas tem que ser um inteiro maior ou igual que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            unidadeTempo = Double.parseDouble(unidadeTempoInput.getText());
        }
        catch (NumberFormatException e) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "A unidade de tempo tem que ser um inteiro maior que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);

        }
        
        if (unidadeTempo <= 0) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "A unidade de tempo tem que ser um inteiro maior que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            unidadesLimite = Double.parseDouble(unidadesLimiteInput.getText());
        }
        catch (NumberFormatException e) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "O número de unidades de tempo limite tem que ser um inteiro maior que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);

        }
        
        if (unidadesLimite <= 0) {
            sucesso = false;
            JOptionPane.showMessageDialog(this, "O número de unidades de tempo limite tem que ser um inteiro maior que 0", "Valor Introduzido Invalido", JOptionPane.ERROR_MESSAGE);
        }
        
        if (sucesso == true) {
            dispose();

            //Mundo mundo = new Mundo(5, 4, 20, 20);
            Mundo mundo = new Mundo(numeroLobos, numeroOvelhas, largura, comprimento);



            Simulacao sim = new Simulacao(1, unidadesLimite, unidadeTempo, mundo);
            //Simulacao sim = new Simulacao(1, 60, 1, mundo);
            //Simulacao sim = new Simulacao(1, 5000, 0.024, mundo);

            sim.run();

        }
    }//GEN-LAST:event_SimularButtonActionPerformed

    private void numeroOvelhasInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroOvelhasInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroOvelhasInputActionPerformed

    private void numeroLobosInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroLobosInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroLobosInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaNovoMundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaNovoMundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaNovoMundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaNovoMundo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaNovoMundo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SimularButton;
    private javax.swing.JTextField comprimentoInput;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField larguraInput;
    private javax.swing.JTextField numeroLobosInput;
    private javax.swing.JTextField numeroOvelhasInput;
    private javax.swing.JTextField unidadeTempoInput;
    private javax.swing.JTextField unidadesLimiteInput;
    // End of variables declaration//GEN-END:variables
}
